### PR TITLE
AmazonQ: Add  start url to more telemetry events of Amazon Q

### PR DESCRIPTION
**Pull request by leigaol**
## Problem

This is a follow up of  https://github.com/aws/aws-toolkit-vscode/pull/4439.  I found some other events that need start url. 

Reviewers, please let me know what event does not need a start url, I can remove it.

The credential start url: 
    It is the current active start url.
    If auth expired, there won't be any startUrl. User with expired auth won't be able to invoke the Code path in Q that sends out any telemetry. Without a valid auth, they won't be able to interact with this product at all. Without any valid user interaction, there won't be any telemetry data.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/toolkit/src/shared/telemetry/vscodeTelemetry.json [hunk 1]
```diff
@@ -861,6 +861,132 @@
...
+            ]
+        },
+        {
+            "name": "amazonq_codeGenerationThumbsUp",
+            "description": "User clicked on the thumbs up button to say that they are unsatisfied",
+            "unit": "Count",
+            "metadata": [
+                { "type": "amazonqConversationId" },
+                {
+                    "type": "credentialStartUrl",
```
[the remark this answers is not in the document]
Comment (leigaol) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: No. 

I made the change in toolkit common in v1.0.91, I tried to update the common dependency version. However, there are significant differences between 1.0.86 and 1.0.91. If I do this upgrade, I will have a lot of conflicts and missing definitions. It seems like the Amazon Q telemetry has diverged a lot from using common. Therefore, I have to override them. 

Overriding the definition has to continue until all Q telemetry has been completely moved to common. THere is a ticket tracking that.

[the remark this answers is not in the document]
Comment (leigaol) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: By doing a diff between the definition override and common, you will find a huge diff and I won't be able to move them in this PR.

[the remark this answers is not in the document]
Comment (leigaol) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: The current consumed 1.0.86 common library has a old version of Q telemetry. For some reason, new Q telemetry events are not pushed to common library anymore, they are pushed as override in toolkit repo. This diverge happened weeks ago and the diff has been growing.

Due to this diff, when adding a new field in Q telemetry events, I cannot just add them to common repo (within a short amount of time). It takes too much due diligence to cherry pick and merge the override and common library. Instead I just push my changes to override json.

[the remark this answers is not in the document]
Comment (hayemaxi) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: not sure if I understand how the override works in comparison to whats in common. Why can't you just move everything here in the override to the commons definitions? Why do you need to cherry pick?

[the remark this answers is not in the document]
Comment (leigaol) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: >Why can't you just move everything here in the override to the commons definitions? 

They cannot be easily moved. There are field in common but not in override. There are field in override but not in common. It is up to Q team to decide which field they want to pick and which they no longer need.

[the remark this answers is not in the document]
Comment (leigaol) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: My VS Code compile immediately breaks when I upgrade common to 1.0.91 latest. .. 

This field https://github.com/aws/aws-toolkit-common/blob/main/telemetry/definitions/commonDefinitions.json#L801 is not in toolkit code, it is required however, it breaks the code if I upgrade.

[the remark this answers is not in the document]
Comment (leigaol) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: amazonq_startChat was in v1.0.86, however, it was removed in common in latest commit https://github.com/aws/aws-toolkit-common/blob/main/telemetry/definitions/commonDefinitions.json#L801

There are lots of Q events that were removed from common, some are kept in common. Some are in override. 

I have no idea why things were moved around. If I move them to common repo, things may break.

**Review by hayemaxi — APPROVED** [review]

File: packages/toolkit/src/shared/telemetry/vscodeTelemetry.json (hunk 1 above)
[the remark this answers is not in the document]
Comment (leigaol) [reply packages/toolkit/src/shared/telemetry/vscodeTelemetry.json:878]: You can see that I clearly tried to add this field in commons 

https://github.com/aws/aws-toolkit-common/blob/11775c057565eb70cc46b5df999566363baeaa41/telemetry/definitions/commonDefinitions.json#L2895


But I find out the common master branch has conflicts with toolkit master branch, if I do this upgrade, there will be 3 compilation errors. These need to be fixed.
